---
  difficulty:
    easy:
      crew_size: 10
      rooms:
        - type: WATER_PLANT
          capacity: 5
          hp: 100
          efficiency: 100
          state: "NOMINAL"

        - type: ELECTRICAL_PLANT
          capacity: 5
          hp: 100
          efficiency: 100
          state: "NOMINAL"

        - type: OXYGEN_PLANT
          capacity: 5
          hp: 100
          efficiency: 100
          state: "NOMINAL"

        - type: FARMING_PLANT
          capacity: 5
          hp: 100
          efficiency: 100
          state: "NOMINAL"

        - type: MACHINE_ROOM
          capacity: 5
          hp: 100
          efficiency: 100
          state: "NOMINAL"

        - type: HQ
          capacity: 5
          hp: 100
          efficiency: 100
          state: "NOMINAL"

        - type: TRAPDOOR
          capacity: 1
          hp: 1000
          efficiency: 100
          state: "NOMINAL"

      ressources:
        OXYGEN: 100
        WATER: 100
        FOOD: 100
        ELECTRICITY: 100
...
